<?php

namespace SfWebApp\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FavoritedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoritedRepository extends EntityRepository
{
}
