<?php

namespace SfWebApp\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FavsIdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavsIdRepository extends EntityRepository
{
}
