<?php

namespace SfWebApp\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideosRepository extends EntityRepository
{
}
