services:
    user.form.profile.type:
        class: SfWebApp\FrontOfficeBundle\Form\Type\ProfileType
        parent: fos_user.profile.form.type
        tags:
            - { name: form.type, alias: sf_web_app_fos_user_profile }

    user.form.register.type:
        class: SfWebApp\FrontOfficeBundle\Form\Type\RegisterType
        parent: fos_user.registration.form.type
        tags:
            - { name: forgm.type, alias: sf_web_app_fos_user_register }