sf_web_app_main_products:
    resource: "@SfWebAppMainBundle/Controller/ProductsController.php"
    type:     annotation

sf_web_app_front_office:
    resource: "@SfWebAppFrontOfficeBundle/Controller/"
    type:     annotation
    prefix:   /

sf_web_app_back_office:
    resource: "@SfWebAppBackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /connect

sf_web_app_main:
    resource: "@SfWebAppMainBundle/Controller/"
    type:     annotation
    prefix:   /admin


