sf_web_app_front_office:
    resource: "@SfWebAppFrontOfficeBundle/Controller/"
    type:     annotation
    prefix:   /

sf_web_app_main:
    resource: "@SfWebAppMainBundle/Controller/"
    type:     annotation
    prefix:   /admin


