# PROFILE
fos_user_profile_show:
    path: /profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    requirements:

fos_user_profile_edit:
    path: /profile/editer
    defaults: { _controller: FoulquierInfoFrontOfficeBundle:Profile:edit }
    requirements:
      methods: [GET|POST]